apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
  labels:
    app: simple
spec:
  selector:
    matchLabels:
      app: simple
  replicas: 1
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: gcr.io/zeebe-io/starter:release-8-2-0-alpha1
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.brokerUrl=release-8-2-0-alpha1-zeebe-gateway:26500
              -Dapp.starter.rate=100
              -Dzeebe.client.requestTimeout=62000
              -XX:+HeapDumpOnOutOfMemoryError
              -Dapp.starter.bpmnXmlPath=bpmn/simpleProcess.bpmn
              -Dapp.starter.processId=simpleProcess
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: release-8-2-0-alpha1
    app.kubernetes.io/name: zeebe-cluster
  name: simple
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: simple
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
