apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  selector:
    matchLabels:
      app: publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: gcr.io/zeebe-io/starter:zell-investigate-2
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.brokerUrl=zell-investigate-2-mixed-zeebe-gateway:26500
              -Dapp.starter.rate=50
              -Dzeebe.client.requestTimeout=62000
              -XX:+HeapDumpOnOutOfMemoryError
              -Dapp.starter.bpmnXmlPath=bpmn/msg_one_task.bpmn
              -Dapp.starter.startViaMessage=true
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: zell-investigate-2-mixed
    app.kubernetes.io/name: zeebe-cluster
  name: publisher
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: publisher
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
